# Generated by Django 3.2.6 on 2021-08-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('spot', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Tourspot')),
                ('cont', models.TextField(verbose_name='content')),
                ('tourimg', models.CharField(max_length=100, verbose_name='image')),
                ('dep', models.CharField(max_length=100, verbose_name='place')),
                ('yea', models.IntegerField(null=True, verbose_name='year')),
                ('mont', models.IntegerField(null=True, verbose_name='month')),
            ],
            options={
                'verbose_name': '여행지',
                'verbose_name_plural': '여행지들',
                'db_table': 'Datas',
            },
        ),
    ]
